environment               = "dev"
resource_group_name       = "app-rg"
location                  = "Central India"
container_image_version   = "v1.0.6"
client_image_version      = "v1.0.7"
container_registry_server = "insurancecr.azurecr.io"

# Set with TF_VAR_jwt_secret or replace this placeholder before apply.
jwt_secret = "MyInsuranceJwtSecret2026"

# For private ACR pulls, set these with TF_VAR_container_registry_username/password.
container_registry_username = "insurancecr"
container_registry_password = "7CAk8EHJlJ3HAn5CEiCFMN28fzaO4QEdSCdonyffFLOzzYJKd1cFJQQJ99CFACGhslBEqg7NAAACAZCRIvxD"

email_domain_name       = "AzureManagedDomain"
email_domain_management = "AzureManaged"

# Azure AI Document Intelligence — must be globally unique
doc_intelligence_name = "aegis-docai-aswin3"

# Storage account — must be globally unique, 3-24 chars, lowercase only
storage_account_name_prefix = "aegishealthst"

# ACS sender address — UPDATE THIS after running `terraform apply` once.
# The actual value will be: DoNotReply@<auto-generated-guid>.azurecomm.net
# Find it in the Azure Portal under: Communication Services > Email domains > MailFrom addresses
acs_sender_address = "DoNotReply@AzureManagedDomain"

tags = {
  owner = "platform"
}

